### ISSUE TITLE
Node.JS APIError

### ISSUE THREAD

**Issue by tristancaron** [auth0/auth0.js#437]
Code snippet or sample project that reproduces the bug:

```ts
export interface OAuthToken {
    access_token: string;
    token_type: string;
    expire_in: number;
    scope: string;
}

function getOAuthToken(): Promise<OAuthToken> {
    const options = {
        method: 'POST',
        url: 'https://my-domain.eu.auth0.com/oauth/token',
        headers: {
            'content-type': 'application/json'
        },
        body: {
            grant_type: 'client_credentials',
            client_id: 'my-id',
            client_secret: 'my-secret',
            audience: 'https://my-domain.eu.auth0.com/api/v2/'
        },
        json: true,
    };

    return request(options).promise());
}
```

This works:

```ts
export function getUser(id: string): User {
    return getOAuthToken()
        .then(payload => {
            const options = {
                method: 'GET',
                url: `https://my-domain.eu.auth0.com/api/v2/users/${id}`,
                headers: {
                    authorization: `Bearer ${payload.access_token}`,
                    'content-type': 'application/json'
                },
                json: true,
            };
            
            return request(options);
        })
        .catch(console.error.bind(console));
}
```

This doesn't work:

```ts
export function getUser(id: string): User {
    return getOAuthToken()
        .then(payload => {
            const client = new ManagementClient({token: payload.access_token, domain: "https://my-domain.eu.auth0.com"});
            return client.getUser({id}).catch(error => console.log(error));
        })
        .catch(console.error.bind(console));
}
```

it throws:

```
{ Error
    at /home/titirex/Projects/DSP_API/node_modules/rest-facade/src/Client.js:295:21
    at Request.callback (/home/titirex/Projects/DSP_API/node_modules/superagent/lib/node/index.js:688:3)
    at ClientRequest.<anonymous> (/home/titirex/Projects/DSP_API/node_modules/superagent/lib/node/index.js:615:10)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at connectErrorNT (net.js:1028:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) name: 'APIError', message: '{}', statusCode: undefined }
TypeError: Cannot read property 'name' of undefined
    at user (/home/titirex/Projects/DSP_API/dist/server.js:1450:35)
    at process._tickCallback (internal/process/next_tick.js:109:7)

```

I'm under MacOS, using Node.JS 7.10.0 and Auth0.js 2.6.0

**Comment by luisrudge** [comment]
Hi, this library is meant to be used in the browser. The node sdk is located here: https://github.com/auth0/node-auth0
