### ISSUE TITLE
WebAuth.parseHash Unhandled Promise Rejection

### ISSUE THREAD

**Issue by tobiasetter** [auth0/auth0.js#594]
Since I implemented server side rendering (aka Angular Universal) I got an error related to auth0-js WebAuth.parseHash Function.

Framework: Angular 5
Browser: Firefox, Chrome, IE
OS: Windows 10, Windows 7

I got the following error:

`ERROR { TypeError: Cannot read property 'location' of undefined
    at WebAuth.parseHash (C:\Dev\frontend\node_modules\auth0-js\src\web-auth\index.js:138:53)
    at e.handleAuthentication (C:\Dev\frontend\dist\server.js:8:523298)
    at new e (C:\Dev\frontend\dist\server.js:8:161974)
    at createClass (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:12509:20)
    at createDirectiveInstance (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:12
)
    at createViewNodes (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:13815:53)
    at createRootView (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:13704:5)
    at Object.createProdRootView [as createRootView] (C:\Dev\frontend\node_modules\@angular\core\
s\core.umd.js:14397:12)
    at ComponentFactory_.create (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:1
6)
    at ComponentFactoryBoundToModule.create (C:\Dev\frontend\node_modules\@angular\core\bundles\c
d.js:4070:29)
  __zone_symbol__currentTask:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
Unhandled Promise rejection: Cannot read property 'location' of undefined ; Zone: <root> ; Task:
Promise.then ; Value: { TypeError: Cannot read property 'location' of undefined
    at WebAuth.parseHash (C:\Dev\frontend\node_modules\auth0-js\src\web-auth\index.js:138:53)
    at e.handleAuthentication (C:\Dev\frontend\dist\server.js:8:523298)
    at new e (C:\Dev\frontend\dist\server.js:8:161974)
    at createClass (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:12509:20)
    at createDirectiveInstance (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:12
354:37)
    at createViewNodes (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:13815:53)
    at createRootView (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:13704:5)
    at Object.createProdRootView [as createRootView] (C:\Dev\frontend\node_modules\@angular\core\
bundles\core.umd.js:14397:12)
    at ComponentFactory_.create (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:1
1299:46)
    at ComponentFactoryBoundToModule.create (C:\Dev\frontend\node_modules\@angular\core\bundles\c
ore.umd.js:4070:29)
  __zone_symbol__currentTask:
   ZoneTask {
     _zone:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } } TypeError: Cannot read property 'location' of undefined
    at WebAuth.parseHash (C:\Dev\frontend\node_modules\auth0-js\src\web-auth\index.js:138:53)
    at e.handleAuthentication (C:\Dev\frontend\dist\server.js:8:523298)
    at new e (C:\Dev\frontend\dist\server.js:8:161974)
    at createClass (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:12509:20)
    at createDirectiveInstance (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:12
354:37)
    at createViewNodes (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:13815:53)
    at createRootView (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:13704:5)
    at Object.createProdRootView [as createRootView] (C:\Dev\frontend\node_modules\@angular\core\
bundles\core.umd.js:14397:12)
    at ComponentFactory_.create (C:\Dev\frontend\node_modules\@angular\core\bundles\core.umd.js:1
1299:46)
    at ComponentFactoryBoundToModule.create (C:\Dev\frontend\node_modules\@angular\core\bundles\c
ore.umd.js:4070:29)`

Does someone know how to fix this error?

If I run `ng serve` I do not get this error.

Many thanks!

**Comment by luisrudge** [comment]
auth0.js doesn't support SSR. `parseHash` will try to parse the hash inside the `window.location.hash` property, which won't be available on the server.

**Comment by rwaldvogel** [comment]
Do you plan to support SSR? Since I am running into the same problem using SSR to speedup first page loading time.
Do you plan to offer an Angular(5+) module?

**Comment by luisrudge** [comment]
This project won’t blow up if you import it on the server, but you can’t call any of the methods from the server. There’s no way we can support that because we need local storage, iframes, window.location and a few more objects that are only available in the browser.

**Comment by rwaldvogel** [comment]
I wasn't saying it blows up - just as you stated, it can not be used with SSR, since it hard coded uses browser dependencies - which is totally fine, regarding that your use case for this module.
And thanks for your answer 👍
