### ISSUE TITLE
Cannot read property 'crypto' of undefined

### ISSUE THREAD

**Issue by vpanugaling** [auth0/auth0.js#741]
I'm getting an error when sending a passwordless link to an email. I'm not sure if it was my setup but it looks like there's a problem in node's `global.window` object as it's not returning anything.

``TypeError: Cannot read property 'crypto' of undefined
    at Object.randomString (/Users/Admin/Documents/WorkSpace/identity/node_modules/auth0-js/src/helper/random.js:9:43)
    at TransactionManager.generateTransaction (/Users/Admin/Documents/WorkSpace/identity/node_modules/auth0-js/src/web-auth/transaction-manager.js:44:27)
    at TransactionManager.process (/Users/Admin/Documents/WorkSpace/identity/node_modules/auth0-js/src/web-auth/transaction-manager.js:19:26)
    at WebAuth.passwordlessStart (/Users/Admin/Documents/WorkSpace/identity/node_modules/auth0-js/src/web-auth/index.js:508:48)
    at /Users/Admin/Documents/WorkSpace/identity/routes.js:109:17
    at Layer.handle [as handle_request] (/Users/Admin/Documents/WorkSpace/identity/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/Admin/Documents/WorkSpace/identity/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/Admin/Documents/WorkSpace/identity/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/Admin/Documents/WorkSpace/identity/node_modules/express/lib/router/layer.js:95:5)
    at /Users/Admin/Documents/WorkSpace/identity/node_modules/express/lib/router/index.js:281:22``

**auth0.js/src/helper/random.js**
Line 9: ``var cryptoObj = windowHelper.getWindow().crypto || windowHelper.getWindow().msCrypto;``

Auth0 JS Version: 9.4.2
Node Version: 9.10.1
Express Version: 4.16.2

**Comment by luisrudge** [comment]
auth0.js is not meant to be used in nodejs. use https://github.com/auth0/node-auth0
