### ISSUE TITLE
crossOriginVerification function is not working

### ISSUE THREAD

**Issue by NaumenkoSergiy** [auth0/auth0.js#780]
https://github.com/auth0/auth0.js/blob/85d20bbae19707ade6c8a9126d248bf7a0e7036e/example/callback-cross-auth.html#L13

`Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'undefined' in a call to 'postMessage'.
    at r.callback (https://cdn.auth0.com/js/auth0/9.0.0/auth0.min.js:9:14964)
    at r.crossOriginVerification (https://cdn.auth0.com/js/auth0/9.0.0/auth0.min.js:12:307)
    at file:///Users/serhiinaumenko/Downloads/test.html:13:11`

**Comment by NaumenkoSergiy** [comment]
@luisrudge Browser Version 67.0.3396.87 (Official Build) (64-bit)
OS - macOS High Sierra Version 10.13.4
I don't use custom domains and running this page on an https endpoint

but the same problem:

`Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'undefined' in a call to 'postMessage'.`

**Comment by luisrudge** [comment]
Do you have the same issue in this page? http://brucke.club/

**Comment by luisrudge** [comment]
Can you send snippets on how you're using it?

**Comment by NaumenkoSergiy** [comment]
I haven't the same issue in  http://brucke.club/
but have in:
https://brucke.club/callback-cross-auth.html

I'm using this code:
`<head>
  <script src="https://cdn.auth0.com/js/auth0/9.5.1/auth0.min.js"></script>
  <script type="text/javascript">
    var auth0 = new auth0.WebAuth({
      clientID: CLIENT_ID,
      domain: domain
    });
    auth0.crossOriginVerification();
  </script>
</head>
`

**Comment by luisrudge** [comment]
Can you describe what are you trying to do? When does `crossOriginVerification` gets called in your authentication flow?

**Comment by NaumenkoSergiy** [comment]
I need this page for Cross-Origin Verification Fallback, I just created callback-cross-auth.html file in public folder and check if it's working but when try to open the page - have the error in console

**Comment by luisrudge** [comment]
That's expected. This page is meant to be called as part of the cross origin authentication fallback (which gets called by Auth0's servers). You can't call it directly. If you have more questions, please reach out to our amazing support team at https://support.auth0.com

**Comment by NaumenkoSergiy** [comment]
Okay, thanks a lot
